# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0423\u0441\u043b\u0443\u0433\u0438')),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0432\u0430\u0439\u0434\u0435\u0440\u0430')),
                ('img', models.ImageField(upload_to=b'uoloads_provaider/', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f')),
                ('account', models.IntegerField(unique=True, verbose_name='\u043b/\u0441 \u043f\u0440\u043e\u0432\u0430\u0439\u0434\u0435\u0440\u0430')),
                ('description', models.TextField(verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u043f\u0440\u043e\u0432\u0430\u0439\u0434\u0435\u0440\u0435')),
                ('display', models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c/\u041e\u0442\u043a\u043b\u044e\u0447\u0438\u0442\u044c')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Categorie')),
            ],
        ),
    ]
